server:
  port: 8180

commercetools:
  projectKey: ${env.commercetools.projectKey}
  authUrl: https://auth.europe-west1.gcp.commercetools.com
  apiUrl: https://api.europe-west1.gcp.commercetools.com
  clientConfig:
    payment:
      clientId: ${env.commercetools.clientConfig.payment.clientId}
      secret: ${secrets.commercetools.clientConfig.payment.secret}
  extension:
    security:
      user: isv-ct-extension
      password: Passw0rd
    features:
      DECISION_MANAGER:
        enabled: true

isv:
  payments:
    client:
      merchantID: ${env.isv.payments.merchantID}
      developerID: ${env.isv.payments.developerID}
      environment: TEST
      keysDirectory: ${env.isv.payments.keysDirectory}
      keyPassword: ${secrets.isv.payments.keyPassword}
      sharedSecret:
        id: ${env.isv.payments.sharedSecret.id}
        value: ${secrets.isv.payments.sharedSecret.value}
      targetAPIVersion: 1.159
      timeout: 5000
      enableLog: false
      logDirectory: .
      logMaximumSize: 10
      certificateCacheEnabled: true
      runEnvironment: CyberSource.Environment.SANDBOX
      authenticationType: http_signature
      merchantKeyId: ${env.isv.payments.sharedSecret.id}
      merchantsecretKey: ${secrets.isv.payments.sharedSecret.value}
    flex:
      targetOrigins: ${env.isv.payments.flex.targetOrigins}
      verificationKey: ${env.isv.payments.flex.verificationKey}
      connectTimeout: 5000

cardinal:
  apiKey: ${secrets.cardinal.apiKey}
  apiIdentifier: ${secrets.cardinal.apiIdentifier}
  orgUnitId: ${secrets.cardinal.orgUnitId}
  ttlMillis: 900000

---
spring:
  profiles: dev

logging:
  level:
    isv.commercetools.reference.application.controller: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info,health,features

---
spring:
  profiles: proxyps

isv:
  payments:
    client:
      serverURL: http://localhost:8080/commerce/1.x/transactionProcessor

---
spring:
  profiles: proxyct

commercetools:
  apiUrl: http://localhost:8081
