import googlePay from '../../JSON/googlePay.json'
export const payment = 
{
    "id":"6b3158a4-6c72-403e-bda1-48d95367cb02",
    "version":5,
    "lastMessageSequenceNumber":4,
    "createdAt":"2021-12-22T07:46:52.751Z",
    "lastModifiedAt":"2021-12-22T07:46:57.983Z",
    "lastModifiedBy":
    {
        "clientId":"iFOAd29Lew5ADrpakIhQkz_N",
        "isPlatformClient":false,
        "customer":
        {
            "typeId":"customer",
            "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
        }
    },
    "createdBy":
    {
        "clientId":"iFOAd29Lew5ADrpakIhQkz_N",
        "isPlatformClient":false,
        "customer":
        {
            "typeId":"customer",
            "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
        }
    },
    "customer":
    {
        "typeId":"customer",
        "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
    },
    "amountPlanned":
    {
        "type":"centPrecision",
        "currencyCode":"USD",
        "centAmount":googlePay.centAmount,
        "fractionDigits":2
    },
    "paymentMethodInfo":
    {
        "paymentInterface":"cybersource",
        "method":"googlePay",
        "name":
        {
            "en":"Google Pay"
        }
    },
    "custom":
    {
        "type":
        {
            "typeId":"type",
            "id":"87b9d9db-74a3-45d7-8e60-dde669866808"
        },
        "fields":
        {
            "isv_deviceFingerprintId":"8a22fb00-dc63-496b-b0de-9f1d1fd36a50",
            "isv_cardExpiryYear":"2027",
            "isv_token":"eyJzaWduYXR1cmUiOiJNRVFDSURrbGkxSVQzTHpmOGlaVHJqRndyUERudy9PVzB0bzVhQ05MTnZyNFh1Z0NBaUFHMTJCeU1QNXhuTHhhVGErSzBDVFl6TGVycjQ4cmgwN3pFWmJvS3NRRTNnXHUwMDNkXHUwMDNkIiwicHJvdG9jb2xWZXJzaW9uIjoiRUN2MSIsInNpZ25lZE1lc3NhZ2UiOiJ7XCJlbmNyeXB0ZWRNZXNzYWdlXCI6XCJmdGhBZDBzeHg5TzBzWlpSSm5zeWdnTWlkK3E1dFFFZmhvT3kvSTFWUUxYcWRQTVVuN2NWbXR3S3hMU0FhQzVtMWpCbmVDbXNNVUdJbzBEU1VpRFV3cHh0MmE0czlIUFpacU93VE1QOFcrMTFjcy8rSzRXSVh2cEFSSis0RTRRa1pmcEdEYkRUL0N3Q2EyTkhnYnFjU0d3RjlOMkhVY0JJWm1qeGRONE4zeFRXUTYxVitSUnBSd2ZKTVlFZkZqemRSakJsNE1KWXFDbWVyMWh3eUZGemdabTQ5YWtYKzRiRHdzZWlCUWI2L2xIdWljNENlVUlqb296Yml3a092aTVvTkVBeDhWTXp1TURob3FHSnlhdVZDbEVaYjJBZnF4dXlaQk1ZaUFrQSt4SHRzTXdqdUR3bWZBd2NoZTMwSmRxd2V6cXpuNDQyS1didHZROVN4ZGk4U3ZWa1FraVVPVk01V1JTdnBDYW9LTTJMKzN5MyszamRxV0NDVFA1QTZZRWphSExpNHJaSEY2L3VWUVRWZGtEeS80d0lKdkx4KzdvYUJwMVVLTjRXbXNrVEM1MHNmKzFDaUhqSkUxWHZoMzdGODZHK1wiLFwiZXBoZW1lcmFsUHVibGljS2V5XCI6XCJCS3JRSXdQNHRoWkdpNGxoN01seU4xSXlPNTdNb3hoenRJdmU3b2tOd1FaQTB0dk5FZjdoclB1TDEyWGtnWitvc1FxRzJaK3VQNWQ2c3FMV1pVUExkS0VcXHUwMDNkXCIsXCJ0YWdcIjpcInpIUmdWOXVXZ0FkUlk3T1ZTQUpWQUt0b0pLSlZIa01CdGxDVTVJTWtLTW9cXHUwMDNkXCJ9In0=",
            "isv_customerIpAddress":"106.202.150.94",
            "isv_maskedPan":"411111XXXXXX1111",
            "isv_cardExpiryMonth":"12",
            "isv_userAgentHeader":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
            "isv_acceptHeader":"*/*",
            "isv_cardType":"001"
        }
    },
    "paymentStatus":{},
    "transactions":
    [
        {
            "id":"3b141bbf-574d-4c6a-80bd-4bf875762805",
            "timestamp":"2021-12-22T07:46:57.530Z",
            "type":"Authorization",
            "amount":
            {
                "type":"centPrecision",
                "currencyCode":"USD",
                "centAmount":5980,
                "fractionDigits":2
            },
            "interactionId":googlePay.authReversalId,
            "state":"Success"
        }
    ],
    "interfaceInteractions":[]
}

export const cart = 
{
    "type":"Cart",
    "id":"3e6cdfa7-2ad0-4261-9135-e4d0a8ed6a9c",
    "version":11,
    "lastMessageSequenceNumber":1,
    "createdAt":"2021-12-22T07:46:20.541Z",
    "lastModifiedAt":"2021-12-22T07:46:58.887Z",
    "lastModifiedBy":
    {
        "clientId":"iFOAd29Lew5ADrpakIhQkz_N",
        "isPlatformClient":false,
        "customer":
        {
            "typeId":"customer",
            "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
        }
    },
    "createdBy":
    {
        "clientId":"iFOAd29Lew5ADrpakIhQkz_N",
        "isPlatformClient":false,
        "customer":
        {
            "typeId":"customer",
            "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
        }
    },
    "customerId":"88c278f9-82d9-427c-96df-f98a4f23e543",
    "lineItems":
    [
        {
            "id":"213df455-eae9-4cbc-8dca-c3340dafbcc7",
            "productId":"7e3ccfc6-36ee-4995-ab1d-bb5095b08bbe",
            "name":
            {
                "en":"Sherwani"
            },
            "productType":
            {
                "typeId":"product-type",
                "id":"31d56c4e-d578-4dab-a313-780b5f1e7556",
                "version":1
            },
            "productSlug":
            {
                "en":"a1"
            },
            "variant":
            {
                "id":1,
                "sku":"SKU-1",
                "prices":
                [
                    {
                        "value":
                        {
                            "type":"centPrecision",
                            "currencyCode":"EUR",
                            "centAmount":15845,
                            "fractionDigits":2
                        },
                        "id":"1fbaed84-99cc-4922-9776-c1ea3cd553e6",
                        "country":"US"
                    },
                    {
                        "value":
                        {
                            "type":"centPrecision",
                            "currencyCode":"USD",
                            "centAmount":5980,
                            "fractionDigits":2
                        },
                        "id":"68018b50-2c8a-4304-b67a-ae15389be32d",
                        "country":"US"
                    }
                ],
                "images":
                [
                    {
                        "url":"https://ik.imagekit.io/ldqsn9vvwgg/images/505833.jpg",
                        "dimensions":
                        {
                            "w":300,
                            "h":375
                        }
                    }
                ],
                "attributes":[],
                "assets":[]
            },
            "price":
            {
                "value":
                {
                    "type":"centPrecision",
                    "currencyCode":"USD",
                    "centAmount":5980,
                    "fractionDigits":2
                },
                "id":"68018b50-2c8a-4304-b67a-ae15389be32d",
                "country":"US"
            },
            "quantity":1,
            "discountedPricePerQuantity":[],
            "taxRate":
            {
                "name":"test-tax-category",
                "amount":0.2,
                "includedInPrice":true,
                "country":"US",
                "id":"HxMyojUT",
                "subRates":[]
            },
            "addedAt":"2021-12-22T07:46:20.849Z",
            "lastModifiedAt":"2021-12-22T07:46:20.849Z",
            "state":
            [
                {
                    "quantity":1,
                    "state":
                    {
                        "typeId":"state",
                        "id":"438c0901-36c4-41ec-9a86-2853d6c73d0d"
                    }
                }],
                "priceMode":"Platform",
                "totalPrice":
                {
                    "type":"centPrecision",
                    "currencyCode":"USD",
                    "centAmount":5980,
                    "fractionDigits":2
                },
                "taxedPrice":
                {
                    "totalNet":
                    {
                        "type":"centPrecision",
                        "currencyCode":"USD",
                        "centAmount":4983,
                        "fractionDigits":2
                    },
                    "totalGross":
                    {
                        "type":"centPrecision",
                        "currencyCode":"USD",
                        "centAmount":5980,
                        "fractionDigits":2
                    }
                },
                "lineItemMode":"Standard"
            }
        ],
        "cartState":"Ordered",
        "totalPrice":
        {
            "type":"centPrecision",
            "currencyCode":"USD",
            "centAmount":5980,
            "fractionDigits":2
        },
        "taxedPrice":
        {
            "totalNet":
            {
                "type":"centPrecision",
                "currencyCode":"USD",
                "centAmount":4983,
                "fractionDigits":2
            },
            "totalGross":
            {
                "type":"centPrecision",
                "currencyCode":"USD",
                "centAmount":5980,
                "fractionDigits":2
            },
            "taxPortions":
            [
                {
                    "rate":0.2,
                    "amount":
                    {
                        "type":"centPrecision",
                        "currencyCode":"USD",
                        "centAmount":997,
                        "fractionDigits":2
                    },
                    "name":"test-tax-category"
                }
            ]
        },
        "country":"US",
        "customLineItems":[],
        "discountCodes":[],
        "paymentInfo":
        {
            "payments":
            [
                {
                    "typeId":"payment",
                    "id":"6b3158a4-6c72-403e-bda1-48d95367cb02"
                }
            ]
        },
        "inventoryMode":"None",
        "taxMode":"Platform",
        "taxRoundingMode":"HalfEven",
        "taxCalculationMode":"LineItemLevel",
        "deleteDaysAfterLastModification":90,
        "refusedGifts":[],
        "origin":"Customer",
        "shippingAddress":
        {
            "firstName":"shakshi",
            "lastName":"poddar",
            "streetName":"1295 Charleston Road",
            "additionalStreetInfo":"5th lane",
            "postalCode":"94043",
            "city":"Mountain View",
            "region":"CA",
            "country":"US",
            "phone":"08808906634",
            "email":"shakshi.poddar@wipro.com"
        },
        "billingAddress":
        {
            "firstName":"shakshi",
            "lastName":"poddar",
            "streetName":"1295 Charleston Road",
            "additionalStreetInfo":"5th lane",
            "postalCode":"94043",
            "city":"Mountain View",
            "region":"CA",
            "country":"US",
            "phone":"08808906634",
            "email":"shakshi.poddar@wipro.com"
        },
        "itemShippingAddresses":[]
    }

export const authReversalId= googlePay.authReversalId

export const authReversalID = '640159216998640950395';


    export const payments = 
    {
        "id":"6b3158a4-6c72-403e-bda1-48d95367cb02",
        "version":5,
        "lastMessageSequenceNumber":4,
        "createdAt":"2021-12-22T07:46:52.751Z",
        "lastModifiedAt":"2021-12-22T07:46:57.983Z",
        "lastModifiedBy":
        {
            "clientId":"iFOAd29Lew5ADrpakIhQkz_N",
            "isPlatformClient":false,
            "customer":
            {
                "typeId":"customer",
                "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
            }
        },
        "createdBy":
        {
            "clientId":"iFOAd29Lew5ADrpakIhQkz_N",
            "isPlatformClient":false,
            "customer":
            {
                "typeId":"customer",
                "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
            }
        },
        "customer":
        {
            "typeId":"customer",
            "id":"88c278f9-82d9-427c-96df-f98a4f23e543"
        },
        "amountPlanned":
        {
            "type":"centPrecision",
            "currencyCode":"USD",
            "centAmount":googlePay.centAmountValue,
            "fractionDigits":2
        },
        "paymentMethodInfo":
        {
            "paymentInterface":"cybersource",
            "method":"googlePay",
            "name":
            {
                "en":"Google Pay"
            }
        },
        "custom":
        {
            "type":
            {
                "typeId":"type",
                "id":"87b9d9db-74a3-45d7-8e60-dde669866808"
            },
            "fields":
            {
                "isv_deviceFingerprintId":"8a22fb00-dc63-496b-b0de-9f1d1fd36a50",
                "isv_cardExpiryYear":"2027",
                "isv_token":"eyJzaWduYXR1cmUiOiJNRVFDSURrbGkxSVQzTHpmOGlaVHJqRndyUERudy9PVzB0bzVhQ05MTnZyNFh1Z0NBaUFHMTJCeU1QNXhuTHhhVGErSzBDVFl6TGVycjQ4cmgwN3pFWmJvS3NRRTNnXHUwMDNkXHUwMDNkIiwicHJvdG9jb2xWZXJzaW9uIjoiRUN2MSIsInNpZ25lZE1lc3NhZ2UiOiJ7XCJlbmNyeXB0ZWRNZXNzYWdlXCI6XCJmdGhBZDBzeHg5TzBzWlpSSm5zeWdnTWlkK3E1dFFFZmhvT3kvSTFWUUxYcWRQTVVuN2NWbXR3S3hMU0FhQzVtMWpCbmVDbXNNVUdJbzBEU1VpRFV3cHh0MmE0czlIUFpacU93VE1QOFcrMTFjcy8rSzRXSVh2cEFSSis0RTRRa1pmcEdEYkRUL0N3Q2EyTkhnYnFjU0d3RjlOMkhVY0JJWm1qeGRONE4zeFRXUTYxVitSUnBSd2ZKTVlFZkZqemRSakJsNE1KWXFDbWVyMWh3eUZGemdabTQ5YWtYKzRiRHdzZWlCUWI2L2xIdWljNENlVUlqb296Yml3a092aTVvTkVBeDhWTXp1TURob3FHSnlhdVZDbEVaYjJBZnF4dXlaQk1ZaUFrQSt4SHRzTXdqdUR3bWZBd2NoZTMwSmRxd2V6cXpuNDQyS1didHZROVN4ZGk4U3ZWa1FraVVPVk01V1JTdnBDYW9LTTJMKzN5MyszamRxV0NDVFA1QTZZRWphSExpNHJaSEY2L3VWUVRWZGtEeS80d0lKdkx4KzdvYUJwMVVLTjRXbXNrVEM1MHNmKzFDaUhqSkUxWHZoMzdGODZHK1wiLFwiZXBoZW1lcmFsUHVibGljS2V5XCI6XCJCS3JRSXdQNHRoWkdpNGxoN01seU4xSXlPNTdNb3hoenRJdmU3b2tOd1FaQTB0dk5FZjdoclB1TDEyWGtnWitvc1FxRzJaK3VQNWQ2c3FMV1pVUExkS0VcXHUwMDNkXCIsXCJ0YWdcIjpcInpIUmdWOXVXZ0FkUlk3T1ZTQUpWQUt0b0pLSlZIa01CdGxDVTVJTWtLTW9cXHUwMDNkXCJ9In0=",
                "isv_customerIpAddress":"106.202.150.94",
                "isv_maskedPan":"411111XXXXXX1111",
                "isv_cardExpiryMonth":"12",
                "isv_userAgentHeader":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
                "isv_acceptHeader":"*/*",
                "isv_cardType":"001"
            }
        },
        "paymentStatus":{},
        "transactions":
        [
            {
                "id":"3b141bbf-574d-4c6a-80bd-4bf875762805",
                "timestamp":"2021-12-22T07:46:57.530Z",
                "type":"Authorization",
                "amount":
                {
                    "type":"centPrecision",
                    "currencyCode":"USD",
                    "centAmount":5980,
                    "fractionDigits":2
                },
                "interactionId":"6401782510106885503955",
                "state":"Success"
            }
        ],
        "interfaceInteractions":[]
    }