spring:
  main:
    web-application-type: NONE

commercetools:
  projectKey: ${env.commercetools.projectKey}
  authUrl: https://auth.sphere.io
  apiUrl: ${env.commercetools.apiUrl}
  clientConfig:
    payment:
      clientId: ${env.commercetools.clientConfig.payment.clientId}
      secret: ${secrets.commercetools.clientConfig.payment.secret}

isv:
  payments:
    client:
      merchantID: ${env.isv.payments.merchantID}
      keysDirectory: ${env.isv.payments.keysDirectory}
      keyPassword: ${secrets.isv.payments.keyPassword}
      sharedSecret:
        id: ${env.isv.payments.sharedSecret.id}
        value: ${secrets.isv.payments.sharedSecret.value}
      targetAPIVersion: 1.159
      timeout: 5000
      enableLog: false
      logDirectory: .
      logMaximumSize: 10
      certificateCacheEnabled: true
      runEnvironment: ${env.isv.payments.runEnvironment}
      authenticationType: http_signature
      merchantKeyId: ${env.isv.payments.sharedSecret.id}
      merchantsecretKey: ${isv.payments.client.sharedSecret.value}
