spring:
  main:
    web-application-type: NONE

commercetools:
  projectKey: ${env.commercetools.projectKey}
  authUrl: https://auth.sphere.io
  apiUrl: ${env.commercetools.apiUrl}
  clientConfig:
    payment:
      clientId: ${env.commercetools.clientConfig.payment.clientId}
      secret: ${secrets.commercetools.clientConfig.payment.secret}

cybersource:
  client:
    merchantID: ${env.cybersource.merchantID}
    keysDirectory: ${env.cybersource.keysDirectory}
    keyPassword: ${secrets.cybersource.keyPassword}
    sharedSecret:
      id: ${env.cybersource.sharedSecret.id}
      value: ${secrets.cybersource.sharedSecret.value}
    targetAPIVersion: 1.159
    timeout: 5000
    enableLog: false
    logDirectory: .
    logMaximumSize: 10
    certificateCacheEnabled: true
    runEnvironment: ${env.cybersource.runEnvironment}
    authenticationType: http_signature
    merchantKeyId: ${env.cybersource.sharedSecret.id}
    merchantsecretKey: ${cybersource.client.sharedSecret.value}
