export const fieldMapperFields = {
    isv_tokenCaptureContextSignature: 'eyJraWQiOiJ6dSIsImFsZyI6IlJTMjU2In0.eyJmbHgiOnsicGF0aCI6Ii9mbGV4L3YyL3Rva2VucyIsImRhdGEihRVWpwa3g1RThRcFhCQUFFSFZpSXVyQjl3NW11ZXBhY0JtcG01UUlyWnNCR1NxQmhheVoyWXM4YS9NbXdTZDg1bEsxZ1g3VmY4Z2dPS1A2VStKU0Qxa3hHMW0vc0lHpXZG4wM2puaFNHaTVIcHpuWTQiLCJvcmlnaW4iOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbSIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiYyIsIm4iOiIzNmJfcDhXZFR1ZVBOdk5jbVBMeGtaakdtUm1ReUFsN25CaU5DWXBBY0dBekZVcW90RU1ndjZfQXRpMDh6SW5fR3VmQ1F3X05kRnFaUXQtaGxoNy1uZ4NGFpMFdkYlY2eThUV0pzYkxhLXdiNWJYM0VKRWFkdjRkdnZGa0lQQ0lqUWV2R1lnUHdLMkI5cUVORUV2VlpCVTFvWXIxU0owbldUZW5RbTFsOXZsdlRDOUhWOWxGJEZjM2VFcxNGZMNlRWN3Rob08taWx4UUo1UFhRdzRyZExrbVl6d1E0VTFTZk96Sml0MW1MMi1RLXFMREFSS3JxRnQ1U1dCY0YtTm94ZXJIaVpHdllUU2xLYjFWcWwW0wZWs0eXRfU1czYXJTc3g1NmtnTFpnQWtLNTEwbjJqVU5BMVEiLCJraWQiOiIwODVQUzhhVkFXakJ5MEM3dEt2aTBQdkdMVUJxSGh2eSJ9fSwiY3R4IjpbeyJkYXdE9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sIm1mT3JpZ2luIjoiaHR0cHM6Ly90ZXN0ZmxleC5jeWJlcnNvdXJjZS5jb20ifSwidHlwZSI6Im1mLiaXNzIjoiRmxleCBBUEkiLCJleHAiOjE2NDE4ODgzMTIsImlhdCI6MTY0MTg4NzQxMiwianRpIjoibFg5eFY5Z25kMTFIcHd4byJ9.DZpFRe8PnMd9WYgL_3419Q4cMkjf-up4teaYxk-xVBSXgo_K9DI7hbnZRFQGSU48NCpIz4MoAQvzjzEYIXIeUDrM5uItkIwYphDynq9vNRYcRmd-b5VYAm1QV5Jrn_gODZmIOV581MuoAZ-zZsYMwidUoPSDrUqAWuUB2KYV5im191t3kVauN_4cqyZM08VLOCjqzThNOq2eSKg95y62JKEP0GI-VnXNujieSBm8Qh1OIDgNym2IGnXBjCw5uD7XsgUwm8xSOPPuEuv4UgHLvxYVm1yqoGuPz7X8zrsZBUYg',
    isv_tokenVerificationContext: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbHgiOnsicGF0aCI6Ii9mbGV4L3YyL3Rva2VucyIsImRhdGEiOiJWpwa3g1RThRcFhCQUFFSFZpSXVyQjl3NW11ZXBhY0JtcG01UUlyWnNCR1NxQmhheVoyWXM4YS9NbXdTZDg1bEsxZ1g3VmY4Z2dPS1A2VStKU0Qxa3hHMW0vc0lFdVZG4wM2puaFNHaTVIcHpuWTQiLCJvcmlnaW4iOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbSIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIsIm4iOiIzNmJfcDhXZFR1ZVBOdk5jbVBMeGtaakdtUm1ReUFsN25CaU5DWXBBY0dBekZVcW90RU1ndjZfQXRpMDh6SW5fR3VmQ1F3X05kRnFaUXQtaGxoNy1uZnlRFpMFdkYlY2eThUV0pzYkxhLXdiNWJYM0VKRWFkdjRkdnZGa0lQQ0lqUWV2R1lnUHdLMkI5cUVORUV2VlpCVTFvWXIxU0owbldUZW5RbTFsOXZsdlRDOUhWOWxGVFljM2VFcxNGZMNlRWN3Rob08taWx4UUo1UFhRdzRyZExrbVl6d1E0VTFTZk96Sml0MW1MMi1RLXFMREFSS3JxRnQ1U1dCY0YtTm94ZXJIaVpHdllUU2xLYjFWcWwzYXZWs0eXRfU1czYXJTc3g1NmtnTFpnQWtLNTEwbjJqVU5BMVEiLCJraWQiOiIwODVQUzhhVkFXakJ5MEM3dEt2aTBQdkdMVUJxSGh2eSJ9fSwiY3R4IjpbeyJkYXRhIyaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sIm1mT3JpZ2luIjoiaHR0cHM6Ly90ZXN0ZmxleC5jeWJlcnNvdXJjZS5jb20ifSwidHlwZSI6Im1mLTAuNzIjoiRmxleCBBUEkiLCJleHAiOjE2NDE4ODgzMTIsImlhdCI6MTY0MTg4NzQxMiwianRpIjoibFg5eFY5Z25kMTFIcHd4byJ9.6KZEcOTyFEI2sM_gShgzdX4C8Xbac'
  }

export const fieldMapperFieldObject =   {
    isv_payerAuthenticationTransactionId: '3G3ZO8q9FwcuodU7LXH0',
    isv_payerAuthenticationRequired: false
  }

  export const visaCardDetailsActionVisaCheckoutData = {
    httpCode: 200,
    billToFieldGroup:  {
      firstName: 'SHAKSHI',
      lastName: 'PODDAR',
      address1: '1295 Charleston Road',
      address2: '5th lane',
      locality: 'Mountain View',
      administrativeArea: 'CA',
      postalCode: '94043',
      email: 'shakshi.poddar@wipro.com',
      country: 'US',
      phoneNumber: '08808906634'
    },
    shipToFieldGroup: {
      firstName: 'SHAKSHI',
      lastName: 'PODDAR',
      address1: '1295 Charleston Road',
      locality: 'Mountain View',
      administrativeArea: 'CA',
      postalCode: '94043',
      country: 'US',
      phoneNumber: '08808906634'
    },
    cardFieldGroup:  {
      suffix: '1111',
      prefix: '411111',
      expirationMonth: '05',
      expirationYear: '25  ',
      type: '001'
    },
    message: null
  }


  export const getOMServiceResponsePaymentResponse = {
    httpCode: 201,
    transactionId: '6420561530596093703954',
    status: 'PENDING',
    message: undefined
  }

  export const getOMServiceResponsePaymentResponseObject = {
    httpCode: 400,
    transactionId: null,
    status: 'INVALID_REQUEST',
    message: undefined
  }

  export const getOMServiceResponseTransactionDetail = {
    id: 'bf72a390-77e6-4748-b099-f253ba0744d9',
    timestamp: '2022-01-13T06:42:30.259Z',
    type: 'Charge',
    amount: {
      type: 'centPrecision',
      currencyCode: 'USD',
      centAmount: 11960,
      fractionDigits: 2
    },
    state: 'Initial'
  }

  export const getAuthResponsePaymentResponse ={
    "httpCode":201,
    "transactionId":"6424036020586494403954",
    "status":"AUTHORIZED",
    "data":
    {
      "_links":
      {
        "self":
        {
          "href":"/pts/v2/payments/6424036020586494403954",
          "method":"GET"
        },
        "capture":
        {
          "href":"/pts/v2/payments/6424036020586494403954/captures",
          "method":"POST"
        }
      },
      "id":"6424036020586494403954",
      "submitTimeUtc":"2022-01-17T07:13:22Z",
      "status":"AUTHORIZED",
      "clientReferenceInformation":
      {
        "code":"ba1914ef-ceef-4e9b-b770-5689592ce65d"
      },
      "processorInformation":
      {
        "approvalCode":"831000",
        "transactionId":"201506041511351",
        "networkTransactionId":"201506041511351",
        "responseCode":"00",
        "avs":
        {
          "code":"1"
        },
        "merchantAdvice":
        {
          "code":"01",
          "codeRaw":"01"
        }
      },
      "paymentAccountInformation":
      {
        "card":
        {
          "type":"001"
        }
      },
      "paymentInformation":
      {
        "card":
        {
          "type":"001"
        },
        "tokenizedCard":
        {
          "type":"001"
        },
        "customer":
        {
          "id":"D55DEE93D3823B34E053AF598E0A2652"
        },
        "paymentInstrument":
        {
          "id":"D55DF05DDCF85EDEE053AF598E0A0056"
        },
        "instrumentIdentifier":
        {
          "id":"7010000000121591111",
          "state":"ACTIVE"
        }},
        "orderInformation":
        {
          "amountDetails":
          {
            "authorizedAmount":"59.80",
            "currency":"USD"
          }
        }
      }
    }

  export const getAuthResponsePaymentResponseObject ={
    "httpCode":201,
    "transactionId":"6424036020586494403954",
    "status":"AUTHORIZED_PENDING_REVIEW",
    "data":
    {
      "_links":
      {
        "self":
        {
          "href":"/pts/v2/payments/6424036020586494403954",
          "method":"GET"
        },
        "capture":
        {
          "href":"/pts/v2/payments/6424036020586494403954/captures",
          "method":"POST"
        }
      },
      "id":"6424036020586494403954",
      "submitTimeUtc":"2022-01-17T07:13:22Z",
      "status":"AUTHORIZED_PENDING_REVIEW",
      "errorInformation":
      {
        "reason":"DECISION_PROFILE_REVIEW",
        "message":"The order is marked for review by Decision Manager"},
      "clientReferenceInformation":
      {
        "code":"ba1914ef-ceef-4e9b-b770-5689592ce65d"
      },
      "processorInformation":
      {
        "approvalCode":"831000",
        "transactionId":"201506041511351",
        "networkTransactionId":"201506041511351",
        "responseCode":"00",
        "avs":
        {
          "code":"1"
        },
        "merchantAdvice":
        {
          "code":"01",
          "codeRaw":"01"
        }
      },
      "paymentAccountInformation":
      {
        "card":
        {
          "type":"001"
        }
      },
      "paymentInformation":
      {
        "card":
        {
          "type":"001"
        },
        "tokenizedCard":
        {
          "type":"001"
        },
        "customer":
        {
          "id":"D55DEE93D3823B34E053AF598E0A2652"
        },
        "paymentInstrument":
        {
          "id":"D55DF05DDCF85EDEE053AF598E0A0056"
        },
        "instrumentIdentifier":
        {
          "id":"7010000000121591111",
          "state":"ACTIVE"
        }},
        "orderInformation":
        {
          "amountDetails":
          {
            "authorizedAmount":"59.80",
            "currency":"USD"
          }
        }
      }
    }

    export const getAuthResponsePaymentDeclinedResponse = 
    {
      "httpCode":201,
      "transactionId":"6437973031316274803954",
      "status":"DECLINED",
      "data":
      {
        "id":"6437973031316274803954",
        "submitTimeUtc":"2022-02-02T10:21:43Z",
        "status":"DECLINED",
        "errorInformation":
        {
          "reason":"DECISION_PROFILE_REJECT",
          "message":"The order has been rejected by Decision Manager"
        },
        "clientReferenceInformation":
        {
          "code":"2d2f0cdb-e057-41f5-81f9-d98da238c3f2"
        },
        "processingInformation":
        {
          "paymentSolution":"012"
        },
        "paymentInformation":
        {
          "scheme":"VISA CREDIT",
          "bin":"411111",
          "accountType":"Visa Gold",
          "issuer":"RIVER VALLEY CREDIT UNION",
          "binCountry":"US"
        },
        "riskInformation":
        {
          "profile":{},
          "infoCodes":
          {
            "customerList":
            [
              "NEG-AFCB","NEG-CC","NEG-EM","NEG-FCB"
            ],
            "deviceBehavior":
            ["KeyMouseDisabled"],
            "suspicious":["RISK-GEO"],
            "globalVelocity":["VELL-FP","VELS-FP","VELS-TIP","VELV-EM"]},
            "casePriority":3,
            "localTime":"0:21:43",
            "score":
            {
              "factorCodes":["F","G","V"],
              "modelUsed":"default",
              "result":"42"
            },
            "providers":{}
          },
          "consumerAuthenticationInformation":{}
        }
      } 

    export const getAuthResponseTransactionDetail = {
      id: 'fa4185f4-3e11-49f8-bbbe-9982e1f7ab68',
      timestamp: '2022-01-17T07:13:19.814Z',
      type: 'Authorization',
      amount: {
        type: 'centPrecision',
        currencyCode: 'USD',
        centAmount: 5980,
        fractionDigits: 2
      },
      state: 'Initial'
    }

    export const getAuthResponsePaymentSuccessResponse =  
    {
      "httpCode":201,
      "transactionId":"B4ZCm7bmq3v7RZ333Yj0",
      "status":"AUTHENTICATION_SUCCESSFUL",
      "data":
      {
        "id":"6437969198926252803955",
        "submitTimeUtc":"2022-02-02T10:15:20Z",
        "status":"AUTHENTICATION_SUCCESSFUL",
        "clientReferenceInformation":
        {
          "code":"a9cf118c-8a3f-4225-8190-6d155d357b22",
          "partner":
          {
            "solutionId":"YBBY8SIG"
          }
        },
        "consumerAuthenticationInformation":
        {
          "authenticationTransactionId":"B4ZCm7bmq3v7RZ333Yj0",
          "directoryServerErrorCode":"101",
          "directoryServerErrorDescription":"Invalid Formatted Message Invalid Formatted Message",
          "ecommerceIndicator":"internet",
          "specificationVersion":"2.1.0",
          "threeDSServerTransactionId":"34cd96a6-4984-4afc-b4dd-fbb6d2e993b4",
          "veresEnrolled":"U"
        }
      },
      "cardinalReferenceId":"aa5120d4-d5f7-4b9d-bea2-1db7aaa6f07c"
    }

    export const getAuthResponsePaymentCompleteResponse = 
    {
      "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmYzhhMzBmNy1jNGEyLTQ0M2YtYmJhNC0wNDQ1M2I3YzE2NmYiLCJpYXQiOjE2NDM3OTY5MTUsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0MzgwMDUxNSwiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUmVmZXJlbmNlSWQiOiJhYTUxMjBkNC1kNWY3LTRiOWQtYmVhMi0xZGI3YWFhNmYwN2MifQ.U5MB8c1PMJRJEnYbY78pWg8Ky4XbPTlVSCUuzmV0r6M",
      "referenceId":"aa5120d4-d5f7-4b9d-bea2-1db7aaa6f07c",
      "deviceDataCollectionUrl":"https://centinelapistag.cardinalcommerce.com/V1/Cruise/Collect",
      "httpCode":201,
      "transactionId":"6437969152436266203954",
      "status":"COMPLETED"
    }

    export const getAuthResponsePaymentPendingResponse = 
    {
      "httpCode":201,
      "transactionId":"NsuSvxr0fOA2eL4b9Uj0",
      "status":"PENDING_AUTHENTICATION",
      "data":
      {
        "id":"6438013048936509503955",
        "submitTimeUtc":"2022-02-02T11:28:25Z",
        "status":"PENDING_AUTHENTICATION",
        "clientReferenceInformation":
        {
          "code":"5bfd0e66-7243-4359-9891-7fce264aaa30",
          "partner":
          {
            "solutionId":"YBBY8SIG"
          }
        },
        "consumerAuthenticationInformation":
        {
          "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJhNzU5ZTkwYy1hMTU1LTRlYTYtYWUzYy1hMmI1NTRkM2E4NDEiLCJpYXQiOjE2NDM4MDEzMDUsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0MzgwNDkwNSwiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovLzBtZXJjaGFudGFjc3N0YWcuY2FyZGluYWxjb21tZXJjZS5jb20vTWVyY2hhbnRBQ1NXZWIvY3JlcS5qc3AiLCJQYXlsb2FkIjoiZXlKdFpYTnpZV2RsVkhsd1pTSTZJa05TWlhFaUxDSnRaWE56WVdkbFZtVnljMmx2YmlJNklqSXVNUzR3SWl3aWRHaHlaV1ZFVTFObGNuWmxjbFJ5WVc1elNVUWlPaUk0TTJVNU1tTTNPUzAyTkRZMkxUUm1Nak10T0RGbU15MHdNRGc1WW1aaU56Z3labVVpTENKaFkzTlVjbUZ1YzBsRUlqb2lOMkkwTW1abVlqSXRZekExTkMwME5EWXhMV0l3TlRNdFptVmtORE5rTWpreU9Ua3dJaXdpWTJoaGJHeGxibWRsVjJsdVpHOTNVMmw2WlNJNklqQXlJbjAiLCJUcmFuc2FjdGlvbklkIjoiTnN1U3Z4cjBmT0EyZUw0YjlVajAifSwiT2JqZWN0aWZ5UGF5bG9hZCI6dHJ1ZSwiUmV0dXJuVXJsIjoiaHR0cHM6Ly95b3V0aGZ1bC1maWVsZC02NDgxMy5wa3RyaW90Lm5ldC9zdW5yaXNlU3BhIn0.jkDqtsLs3oMkRoaJh2Vw5qsTbkk9CEVGOu5g0xGT4bI",
          "acsTransactionId":"7b42ffb2-c054-4461-b053-fed43d292990",
          "acsUrl":"https://0merchantacsstag.cardinalcommerce.com/MerchantACSWeb/creq.jsp",
          "authenticationTransactionId":"NsuSvxr0fOA2eL4b9Uj0",
          "challengeRequired":"N",
          "pareq":"eyJtZXNzYWdlVHlwZSI6IkNSZXEiLCJtZXNzYWdlVmVyc2lvbiI6IjIuMS4wIiwidGhyZWVEU1NlcnZlclRyYW5zSUQiOiI4M2U5MmM3OS02NDY2LTRmMjMtODFmMy0wMDg5YmZiNzgyZmUiLCJhY3NUcmFuc0lEIjoiN2I0MmZmYjItYzA1NC00NDYxLWIwNTMtZmVkNDNkMjkyOTkwIiwiY2hhbGxlbmdlV2luZG93U2l6ZSI6IjAyIn0",
          "specificationVersion":"2.1.0",
          "stepUpUrl":"https://centinelapistag.cardinalcommerce.com/V2/Cruise/StepUp",
          "threeDSServerTransactionId":"83e92c79-6466-4f23-81f3-0089bfb782fe",
          "veresEnrolled":"Y",
          "directoryServerTransactionId":"fff8a722-62a9-471b-8993-a41c91048d22"
        },
        "errorInformation":{
          "reason":"CONSUMER_AUTHENTICATION_REQUIRED",
          "message":"The cardholder is enrolled in Payer Authentication. Please authenticate the cardholder before continuing with the transaction."
        }
      },
      "cardinalReferenceId":"8f0d726c-3c21-447e-a936-d9a5dfc5e57b"
    }
    
    export const getCapturedAmountRefundPaymentObj = {
      id: '5bfd0e66-7243-4359-9891-7fce264aaa30',
      version: 33,
      lastMessageSequenceNumber: 7,
      createdAt: '2022-02-02T11:28:03.285Z',
      lastModifiedAt: '2022-02-02T12:12:31.722Z',
      lastModifiedBy: { clientId: 'iFOAd29Lew5ADrpakIhQkz_N', isPlatformClient: false },
      createdBy: {
        clientId: 'iFOAd29Lew5ADrpakIhQkz_N',
        isPlatformClient: false,
        customer: { typeId: 'customer', id: '88c278f9-82d9-427c-96df-f98a4f23e543' }
      },
      customer: { typeId: 'customer', id: '88c278f9-82d9-427c-96df-f98a4f23e543' },
      amountPlanned: {
        type: 'centPrecision',
        currencyCode: 'USD',
        centAmount: 6970,
        fractionDigits: 2
      },
      paymentMethodInfo: {
        paymentInterface: 'cybersource',
        method: 'creditCardWithPayerAuthentication',
        name: { en: 'Credit Card Payer Authentication' }
      },
      custom: {
        type: { typeId: 'type', id: '87b9d9db-74a3-45d7-8e60-dde669866808' },
        fields: {
          isv_requestJwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiOWM3YzZmNC0xZTliLTRlMTItOGFkNC0yOTIzNWUyY2U1ZTAiLCJpYXQiOjE2NDM4MDEzMDAsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0MzgwNDkwMCwiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUmVmZXJlbmNlSWQiOiI4ZjBkNzI2Yy0zYzIxLTQ0N2UtYTkzNi1kOWE1ZGZjNWU1N2IifQ.wEXK-GCJc62oqrrhAYOca3kuqN1A4dNQh8OmHkSkILc',
          isv_deviceFingerprintId: '9703373f-4385-4f5c-9fa7-de89e7f8e469',
          isv_cardExpiryYear: '2025',
          isv_token: 'eyJraWQiOiIwOFlZeFh4dVl4Y1pvUlA0dEl5MHE0ck5IU28yTjlrNSIsImFsZyI6IlJTMjU2In0.eyJkYXRhIjp7ImV4cGlyYXRpb25ZZWFyIjoiMjAyNSIsIm51bWJlciI6IjQwMDAwMFhYWFhYWDEwOTEiLCJleHBpcmF0aW9uTW9udGgiOiIwMSIsInR5cGUiOiIwMDEifSwiaXNzIjoiRmxleC8wNyIsImV4cCI6MTY0MzgwMjE5OCwidHlwZSI6Im1mLTAuMTEuMCIsImlhdCI6MTY0MzgwMTI5OCwianRpIjoiMUUyQzVCR1pYSllISjA2S1k2TU1GWE5CVVdVU05IUDhTRzM3SDFTTVdPMzAwQTJQU0JPRDYxRkE2RTU2MTVDQiIsImNvbnRlbnQiOnsicGF5bWVudEluZm9ybWF0aW9uIjp7ImNhcmQiOnsiZXhwaXJhdGlvblllYXIiOnsidmFsdWUiOiIyMDI1In0sIm51bWJlciI6eyJtYXNrZWRWYWx1ZSI6IlhYWFhYWFhYWFhYWDEwOTEiLCJiaW4iOiI0MDAwMDAifSwic2VjdXJpdHlDb2RlIjp7fSwiZXhwaXJhdGlvbk1vbnRoIjp7InZhbHVlIjoiMDEifSwidHlwZSI6eyJ2YWx1ZSI6IjAwMSJ9fX19fQ.feBSpCU9jvQAV9y_hOkXb3o4EJN8OvTRXZIXrpuse9iWeRAMrfVAXHYiIeQ5o0mTIqwuLxikGUlVY0Cug3UwvU4zD9fPklDZhE8vApElrkKDbceH2lvAHLswz97IF04PicPqmKbs5vYQ36d-UM0VJo4iQF6vMRN1upfGWU07aaE2sOfK7CAEyQjVD_PoLzRMKobyvBdykq7HfGpEI3hLSPARDd-ZVWpyxTIdHXFHnzQ9vfmCQd1ZMK4FoWk2Rlwqd-_wnIHebFHwzkaNkT31aO4M9HKzNYfISjPGROFwT9L5j9UUfluYmWH2oc0hLy794Hw4KxlyLPokJQgz_s9czA',
          isv_payerAuthenticationPaReq: 'eyJtZXNzYWdlVHlwZSI6IkNSZXEiLCJtZXNzYWdlVmVyc2lvbiI6IjIuMS4wIiwidGhyZWVEU1NlcnZlclRyYW5zSUQiOiI4M2U5MmM3OS02NDY2LTRmMjMtODFmMy0wMDg5YmZiNzgyZmUiLCJhY3NUcmFuc0lEIjoiN2I0MmZmYjItYzA1NC00NDYxLWIwNTMtZmVkNDNkMjkyOTkwIiwiY2hhbGxlbmdlV2luZG93U2l6ZSI6IjAyIn0',
          isv_maskedPan: '400000XXXXXX1091',
          isv_payerAuthenticationTransactionId: 'NsuSvxr0fOA2eL4b9Uj0',
          isv_payerAuthenticationRequired: true,
          isv_acceptHeader: '*/*',
          isv_cardType: '001',
          isv_cardExpiryMonth: '01',
          isv_payerAuthenticationAcsUrl: 'https://0merchantacsstag.cardinalcommerce.com/MerchantACSWeb/creq.jsp',
          isv_responseJwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJhNzU5ZTkwYy1hMTU1LTRlYTYtYWUzYy1hMmI1NTRkM2E4NDEiLCJpYXQiOjE2NDM4MDEzMDUsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0MzgwNDkwNSwiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovLzBtZXJjaGFudGFjc3N0YWcuY2FyZGluYWxjb21tZXJjZS5jb20vTWVyY2hhbnRBQ1NXZWIvY3JlcS5qc3AiLCJQYXlsb2FkIjoiZXlKdFpYTnpZV2RsVkhsd1pTSTZJa05TWlhFaUxDSnRaWE56WVdkbFZtVnljMmx2YmlJNklqSXVNUzR3SWl3aWRHaHlaV1ZFVTFObGNuWmxjbFJ5WVc1elNVUWlPaUk0TTJVNU1tTTNPUzAyTkRZMkxUUm1Nak10T0RGbU15MHdNRGc1WW1aaU56Z3labVVpTENKaFkzTlVjbUZ1YzBsRUlqb2lOMkkwTW1abVlqSXRZekExTkMwME5EWXhMV0l3TlRNdFptVmtORE5rTWpreU9Ua3dJaXdpWTJoaGJHeGxibWRsVjJsdVpHOTNVMmw2WlNJNklqQXlJbjAiLCJUcmFuc2FjdGlvbklkIjoiTnN1U3Z4cjBmT0EyZUw0YjlVajAifSwiT2JqZWN0aWZ5UGF5bG9hZCI6dHJ1ZSwiUmV0dXJuVXJsIjoiaHR0cHM6Ly95b3V0aGZ1bC1maWVsZC02NDgxMy5wa3RyaW90Lm5ldC9zdW5yaXNlU3BhIn0.jkDqtsLs3oMkRoaJh2Vw5qsTbkk9CEVGOu5g0xGT4bI',
          isv_userAgentHeader: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
          isv_tokenVerificationContext: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbHgiOnsicGF0aCI6Ii9mbGV4L3YyL3Rva2VucyIsImRhdGEiOiI3Q0svYUpYR3BlSmNCOXZzUkxlRmVoQUFFQVptdk9JaVorOTlQZTN2MXBqUGdEM3R5VVNnRHdRa2NWZEpBSUs2dmNwUm5QcGVjY3dmbm9pSXlZQ28xZHZuRTQzakF2d2oxcFZTQmtBNVhGbzNQempJcWRnQXE0WlFIQXdwZWVnNnMxSmsiLCJvcmlnaW4iOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbSIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6ImVuYyIsIm4iOiIzYnZ5VjZoUGdzQzlxNGdSRUhwa1ZhSlVFNy1nQkl6YjNOcExFeDlHXzRJMWNsSmhac05DanFiTWVXTUVIbC1iZlNfRk9GVVV1TzhqSnRPdDJud09nN1BtX3R0VEFCMlExUS1nTHlocEF4UmM5ZUYzci1KVzZDS2syUmhTNDZiSlBRc3ZiYm1XaUpkVG96SUhUaFZ3cHhnMHdBVDFhdWhUMWtsTHptSWMtY3AyeWNuRThpZGVLcW92QXNCSDhsZ3k0T2FoWWtmMmM4Y1BCN3owYnFLaVVzcHFHcTBNWExEcEtDaU1xdi1nUmN1MFoxejVLb2RvZlUwTmVvTDJINWNPVjFWMi1jaUdnSHhHVDh6UEpWVU1RX2dKRzNhRTBfUm40ZkR4YjIxeHo4M3V0TDR4c2tDZ29kYjdDU0E3cVVOZGZfQmRzd01TelJXbWxObEdzaVVPOXciLCJraWQiOiIwOFlZeFh4dVl4Y1pvUlA0dEl5MHE0ck5IU28yTjlrNSJ9fSwiY3R4IjpbeyJkYXRhIjp7InRhcmdldE9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sIm1mT3JpZ2luIjoiaHR0cHM6Ly90ZXN0ZmxleC5jeWJlcnNvdXJjZS5jb20ifSwidHlwZSI6Im1mLTAuMTEuMCJ9XSwiaXNzIjoiRmxleCBBUEkiLCJleHAiOjE2NDM4MDIxODIsImlhdCI6MTY0MzgwMTI4MiwianRpIjoiZHB0OXd4ejVOWGxyaUd1eSJ9.6Rx1nETbPUWLXZfaDCCTgfZ_Y1SulD56u3gi9a8_TGA'
        }
      },
      paymentStatus: {},
      transactions: [
        {
          id: 'a66038fa-48ac-49af-ab99-909144d037b0',
          timestamp: '2022-02-02T11:28:37.126Z',
          type: 'Authorization',
          amount: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 6970,
            fractionDigits: 2
        },
          interactionId: '6438013202686533603954',
          state: 'Success'
        },
        {
          id: '0847f181-5631-4d02-b414-40e4f29b7f74',
          timestamp: '2022-02-02T12:12:27.562Z',
          type: 'Charge',
          amount: {
            type: 'centPrecision',
            currencyCode: 'USD',
            centAmount: 6970,
            fractionDigits: 2
        },
          interactionId: '6438039510446950603955',
          state: 'Success'
        }
      ],
      interfaceInteractions: [
        { type: [Object], fields: [Object] },
        { type: [Object], fields: [Object] }
      ]
    }

export const changeStateTransactionDetail = 
{
  id: 'c36b4a64-f2da-4d31-9a98-41a9e82663af',
  timestamp: '2022-03-30T07:22:03.564Z',
  type: 'Charge',
  amount: {
    type: 'centPrecision',
    currencyCode: 'USD',
    centAmount: 6970,
    fractionDigits: 2
  },
  state: 'Initial'
}

export const successState = 'Success'

export const changeStateFailureTransactionDetail =
{
  id: 'fa4185f4-3e11-49f8-bbbe-9982e1f7ab68',
  timestamp: '2022-01-17T07:13:19.814Z',
  type: 'Authorization',
  amount: {
    type: 'centPrecision',
    currencyCode: 'USD',
    centAmount: 5980,
    fractionDigits: 2
  },
  state: 'Initial'
}

export const failureState = 'Failure'

export const payerAuthActionsResponse  =
{
  isv_payerAuthenticationPaReq: 'eNpVUV1vgjAUfe+vMGbP9APEaa5NdGyZZhhl6p5ZaSaJfFhgiL9+LcLc+nTP7bntOefC7qik9N6lqJTk4MuiCL/kII5mw2bxZgdXetqNndJbsf12Q8iQw2YeyDOHb6mKOEs5tYjFAPcQ6SeUOIZpySEU58VyzR13wqgLuIMIEqmWHrcd6jDmMHI7gG9tBGmYSF7HucpOZQS4hQhEVqWlavijo6k9QFCpEz+WZV5MMa7r2hLNp1aSVUpIS2QJYENAgO+qNpWpCm32Ekdc7le+T1eu/3HZr68BCZ6z5nB42frefAbYMBBEYSk5I4wR2yYDSqcOmRpDbR9BmBg1/MGdWGOtrYMIcvPR/Ibcibn629GOKqVkKnpLPUIgL3mWSs3Ruf7W2sNd+dOrSVeUOq8Rc1w6GZt4W9yOxzobNiK0nY/boLCZwd3ycLdnXf3b/w9MkKjU',
  isv_payerAuthenticationTransactionId: 'yBL3Rz1lT74tDJ2UQP00',
  stepUpUrl: 'https://centinelapistag.cardinalcommerce.com/V2/Cruise/StepUp',
  isv_responseJwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkNDlkYTZmMS04NWMxLTQxZTgtYmQ0ZS0wYWQ3ZjM1NzkzNjEiLCJpYXQiOjE2NDg2NDA0MTYsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0ODY0NDAxNiwiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovL21lcmNoYW50YWNzc3RhZy5jYXJkaW5hbGNvbW1lcmNlLmNvbS9NZXJjaGFudEFDU1dlYi9wYXJlcS5qc3A_dmFhPWImZ29sZD1BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEiLCJQYXlsb2FkIjoiZU5wVlVWMXZnakFVZmUrdk1HYlA5QVBFYWE1TmRHeVpaaGhsNnA1WmFTYUpmRmhnaUw5K0xjTGMrblRQN2JudE9lZkM3cWlrOU42bHFKVGs0TXVpQ0wva0lJNW13MmJ4WmdkWGV0cU5uZEpic2YxMlE4aVF3MllleURPSGI2bUtPRXM1dFlqRkFQY1E2U2VVT0lacHlTRVU1OFZ5elIxM3dxZ0x1SU1JRXFtV0hyY2Q2akRtTUhJN2dHOXRCR21ZU0Y3SHVjcE9aUVM0aFFoRVZxV2xhdmlqbzZrOVFGQ3BFeitXWlY1TU1hN3IyaExOcDFhU1ZVcElTMlFKWUVOQWdPK3FOcFdwQ20zMkVrZGM3bGUrVDFldS8zSFpyNjhCQ1o2ejVuQjQyZnJlZkFiWU1CQkVZU2s1STR3UjJ5WURTcWNPbVJwRGJSOUJtQmcxL01HZFdHT3RyWU1JY3ZQUi9JYmNpYm42MjlHT0txVmtLbnBMUFVJZ0wzbVdTczNSdWY3VzJzTmQrZE9yU1ZlVU9xOFJjMXc2R1p0NFc5eU94em9iTmlLMG5ZL2JvTENad2QzeWNMZG5YZjNiL3c5TWtLalUiLCJUcmFuc2FjdGlvbklkIjoieUJMM1J6MWxUNzR0REoyVVFQMDAifSwiT2JqZWN0aWZ5UGF5bG9hZCI6dHJ1ZSwiUmV0dXJuVXJsIjoiaHR0cHM6Ly95b3V0aGZ1bC1maWVsZC02NDgxMy5wa3RyaW90Lm5ldC9wYXllckF1dGhSZXR1cm5VcmwifQ.j1yRw1vkOsXhzyvfDra7ZX0XhDEjzXokxybSpQL3sHM',
  isv_payerAuthenticationRequired: true,
  xid: 'eUJMM1J6MWxUNzR0REoyVVFQMDA=',
  pareq: 'eNpVUV1vgjAUfe+vMGbP9APEaa5NdGyZZhhl6p5ZaSaJfFhgiL9+LcLc+nTP7bntOefC7qik9N6lqJTk4MuiCL/kII5mw2bxZgdXetqNndJbsf12Q8iQw2YeyDOHb6mKOEs5tYjFAPcQ6SeUOIZpySEU58VyzR13wqgLuIMIEqmWHrcd6jDmMHI7gG9tBGmYSF7HucpOZQS4hQhEVqWlavijo6k9QFCpEz+WZV5MMa7r2hLNp1aSVUpIS2QJYENAgO+qNpWpCm32Ekdc7le+T1eu/3HZr68BCZ6z5nB42frefAbYMBBEYSk5I4wR2yYDSqcOmRpDbR9BmBg1/MGdWGOtrYMIcvPR/Ibcibn629GOKqVkKnpLPUIgL3mWSs3Ruf7W2sNd+dOrSVeUOq8Rc1w6GZt4W9yOxzobNiK0nY/boLCZwd3ycLdnXf3b/w9MkKjU',        
  cardinalId: '6ab813c3-8edf-430f-8ec7-62b19209f78f',
  proofXml: '<AuthProof><Time>2022 Mar 30 11:40:16</Time><DSUrl>https://merchantacsstag.cardinalcommerce.com/MerchantACSWeb/vereq.jsp?acqid=CYBS</DSUrl><VEReqProof><Message id="yBL3Rz1lT74tDJ2UQP00"><VEReq><version>1.0.2</version><pan>XXXXXXXXXXXX1091</pan><Merchant><acqBIN>469216</acqBIN><merID>341422420000000</merID><password></password></Merchant><Browser><deviceCategory>0</deviceCategory><accept>*/*</accept><userAgent>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36</userAgent></Browser></VEReq></Message></VEReqProof><VEResProof><Message id="yBL3Rz1lT74tDJ2UQP00"><VERes><version>1.0.2</version><CH><enrolled>Y</enrolled><acctID>5246197</acctID></CH><url>https://merchantacsstag.cardinalcommerce.com/MerchantACSWeb/pareq.jsp?vaa=b&amp;gold=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</url><protocol>ThreeDSecure</protocol></VERes></Message></VEResProof></AuthProof>',
  veresEnrolled: 'Y',
  specificationVersion: '1.0.2',
  acsurl: 'https://merchantacsstag.cardinalcommerce.com/MerchantACSWeb/pareq.jsp?vaa=b&gold=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  authenticationTransactionId: 'yBL3Rz1lT74tDJ2UQP00',
  directoryServerTransactionId: undefined
}

export const payerEnrollActionsResponse =
{
  "httpCode": 201,
  "transactionId": "6486429828526882404951",
  "status": "PENDING_AUTHENTICATION",
  "data": {
    "id": "6486429828526882404951",
    "submitTimeUtc": "2022-03-30T12:23:03Z",
    "status": "PENDING_AUTHENTICATION",
    "errorInformation": {
      "reason": "CONSUMER_AUTHENTICATION_REQUIRED",
      "message": "The cardholder is enrolled in Payer Authentication. Please authenticate the cardholder before continuing with the transaction."
    },
    "clientReferenceInformation": {
      "code": "5c162200-5e31-4857-9778-458b3efc9d77"
    },
    "paymentInformation": {
      "card": {
        "type": "VISA"
      },
      "customer": {
        "id": "DB0B315B52BABC38E053AF598E0A8268"
      },
      "paymentInstrument": {
        "id": "DB0B3127886FBB46E053AF598E0AF2A5"
      },
      "instrumentIdentifier": {
        "id": "7010000000121591111",
        "state": "ACTIVE"
      }
    },
    "consumerAuthenticationInformation": {
      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyOTNlN2IwMy01OTg3LTQ2MjYtOGNmMS1mMDllNzFmZWViNTEiLCJpYXQiOjE2NDg2NDI5ODMsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0ODY0NjU4MywiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovL21lcmNoYW50YWNzc3RhZy5jYXJkaW5hbGNvbW1lcmNlLmNvbS9NZXJjaGFudEFDU1dlYi9wYXJlcS5qc3A_dmFhPWImZ29sZD1BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEiLCJQYXlsb2FkIjoiZU5wVlVjdHV3akFRdlBzckVPbzVkaHdUQ0Zvc1FWRUZWQ0FFcUttNHBZNVZVdkxDU1hqMDYydUhwTFErN2F4bjdabFoyQjJVbE5PdEZKV1NISmF5S0lKUDJZbkNVWmY2L2YwMjNIdUQzZWJNMU8yZDdGOUpsOE42dkpFbkRtZXBpaWhMdVcwUml3SnVJZEpQS0hFSTBwSkRJRTZUK1lvejE2TzJDN2lCQ0JLcDVsUHVNSnRSeWlpNUg4RDNOb0kwU0NTL1JMbks0aklFWEVNRUlxdlNVdDM0Z0dscUN4QlVLdWFIc3N5TEljYVh5OFVTdHcrdEpLdVVrSmJJRXNDR2dBQS9WSzByVXhYYTdEVUsrVElXamgrdmp2N1hrYjI5TE9ocXR1ajUwMG13L1I2UEFCc0dnakFvSmFlRVV1STRwR1BUSVhXR1JIdXUrd2lDeEtqaFQ2NW45YlcyQmlMSXpVZmpPM0k5Yy9XM294MVZTc2xVdEpaYWhFQmU4eXlWbXFQLytLMjFoNGZ5NTVsSlY1UTZyeDVscnUzMVRidzFyc2NqblEzdEVidWVqK3Fnc0puQnpmSndzMmRkL2R2L0Q5amNxUjg9IiwiVHJhbnNhY3Rpb25JZCI6IjJXN1pTZFo5OFRSdjRyeVgwWkswIn0sIk9iamVjdGlmeVBheWxvYWQiOnRydWUsIlJldHVyblVybCI6Imh0dHBzOi8veW91dGhmdWwtZmllbGQtNjQ4MTMucGt0cmlvdC5uZXQvcGF5ZXJBdXRoUmV0dXJuVXJsIn0.uPVslu3p29n3_iILm0_ywbqTmMcqeiMiZHT62qcazDk",
      "acsUrl": "https://merchantacsstag.cardinalcommerce.com/MerchantACSWeb/pareq.jsp?vaa=b&gold=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "authenticationPath": "ENROLLED",
      "authenticationTransactionId": "2W7ZSdZ98TRv4ryX0ZK0",
      "pareq": "eNpVUctuwjAQvPsrEOo5dhwTCFosQVEFVCAEqKm4pY5VUvLCSXj062uHpLQ+7axn7ZlZ2B2UlNOtFJWSHJayKIJP2YnCUZf6/f023HuD3ebM1O2d7F9Jl8N6vJEnDmepiihLuW0RiwJuIdJPKHEI0pJDIE6T+Yoz16O2C7iBCBKp5lPuMJtRyii5H8D3NoI0SCS/RLnK4jIEXEMEIqvSUt34gGlqCxBUKuaHssyLIcaXy8UStw+tJKuUkJbIEsCGgAA/VK0rUxXa7DUK+TIWjh+vjv7Xkb29LOhqtuj500mw/R6PABsGgjAoJaeEUuI4pGPTIXWGRHuu+wiCxKjhT65n9bW2BiLIzUfjO3I9c/W3ox1VSslUtJZahEBe8yyVmqP/+K21h4fy55lJV5Q6rx5lru31Tbw1rscjnQ3tEbuej+qgsJnBzfJws2dd/dv/D9jcqR8=",
      "proofXml": "<AuthProof><Time>2022 Mar 30 12:23:02</Time><DSUrl>https://merchantacsstag.cardinalcommerce.com/MerchantACSWeb/vereq.jsp?acqid=CYBS</DSUrl><VEReqProof><Message id=\"2W7ZSdZ98TRv4ryX0ZK0\"><VEReq><version>1.0.2</version><pan>XXXXXXXXXXXX1091</pan><Merchant><acqBIN>469216</acqBIN><merID>341422420000000</merID><password></password></Merchant><Browser><deviceCategory>0</deviceCategory><accept>*/*</accept><userAgent>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36</userAgent></Browser></VEReq></Message></VEReqProof><VEResProof><Message id=\"2W7ZSdZ98TRv4ryX0ZK0\"><VERes><version>1.0.2</version><CH><enrolled>Y</enrolled><acctID>5246197</acctID></CH><url>https://merchantacsstag.cardinalcommerce.com/MerchantACSWeb/pareq.jsp?vaa=b&amp;gold=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</url><protocol>ThreeDSecure</protocol></VERes></Message></VEResProof></AuthProof>",
      "proxyPan": "5246197",
      "specificationVersion": "1.0.2",
      "stepUpUrl": "https://centinelapistag.cardinalcommerce.com/V2/Cruise/StepUp",
      "veresEnrolled": "Y",
      "xid": "Mlc3WlNkWjk4VFJ2NHJ5WDBaSzA="
    }
  },
  "cardinalReferenceId": "b0c79f37-281e-4f09-a7a1-8ed01a459f20"
}

export const payerEnrollActionsUpdatePaymentObj = 
{
  id: '5c162200-5e31-4857-9778-458b3efc9d77',
  version: 15,
  lastMessageSequenceNumber: 1,
  createdAt: '2022-03-30T12:22:40.466Z',
  lastModifiedAt: '2022-03-30T12:22:57.080Z',
  lastModifiedBy: {
    clientId: '0GrQ8c2D9t1iSjzJF8E3Ygu3',
    isPlatformClient: false,
    customer: { typeId: 'customer', id: 'b0c50186-fc83-4a97-9ea3-47bab58b3cc6' }
  },
  createdBy: {
    clientId: '0GrQ8c2D9t1iSjzJF8E3Ygu3',
    isPlatformClient: false,
    customer: { typeId: 'customer', id: 'b0c50186-fc83-4a97-9ea3-47bab58b3cc6' }
  },
  customer: { typeId: 'customer', id: 'b0c50186-fc83-4a97-9ea3-47bab58b3cc6' },
  amountPlanned: {
    type: 'centPrecision',
    currencyCode: 'USD',
    centAmount: 6970,
    fractionDigits: 2
  },
  paymentMethodInfo: {
    paymentInterface: 'cybersource',
    method: 'creditCardWithPayerAuthentication',
    name: { en: 'Credit Card Payer Authentication' }
  },
  custom: {
    type: { typeId: 'type', id: '87b9d9db-74a3-45d7-8e60-dde669866808' },
    fields: {
      isv_deviceFingerprintId: '5bb99fdb-9c2b-4606-a71c-c45d05a1b812',
      isv_cardExpiryYear: '2025',
      isv_token: 'eyJraWQiOiIwODVJUUxGaENrVmFmcUxLa1RBNnBGMWdIZmNGZ1ROOCIsImFsZyI6IlJTMjU2In0.eyJkYXRhIjp7ImV4cGlyYXRpb25ZZWFyIjoiMjAyNSIsIm51bWJlciI6IjQwMDAwMFhYWFhYWDEwOTEiLCJleHBpcmF0aW9uTW9udGgiOiIwMSIsInR5cGUiOiIwMDEifSwiaXNzIjoiRmxleC8wOCIsImV4cCI6MTY0ODY0Mzg3MywidHlwZSI6Im1mLTAuMTEuMCIsImlhdCI6MTY0ODY0Mjk3MywianRpIjoiMUUwSEI1R1RWNzgwUjk5WEhTWkU5WFVHM0JYQzk2TVRLOFRaNkU0SEVWWVVMMUMxQllYVjYyNDQ0RjIxM0MyQSIsImNvbnRlbnQiOnsicGF5bWVudEluZm9ybWF0aW9uIjp7ImNhcmQiOnsiZXhwaXJhdGlvblllYXIiOnsidmFsdWUiOiIyMDI1In0sIm51bWJlciI6eyJtYXNrZWRWYWx1ZSI6IlhYWFhYWFhYWFhYWDEwOTEiLCJiaW4iOiI0MDAwMDAifSwic2VjdXJpdHlDb2RlIjp7fSwiZXhwaXJhdGlvbk1vbnRoIjp7InZhbHVlIjoiMDEifSwidHlwZSI6eyJ2YWx1ZSI6IjAwMSJ9fX19fQ.DWOWqICszl7KVlzRZLhV0E39cTkK19V8ZpRl-rKfeON6ObxYnwvWu8R-OMI1C6J9U4p0ng44lA7sMcEGqI0Tbl8SNSvbyznxlJLfxMyHmzgYNvLHl0b2aa6B4x_FYSe1YEMlaN_JRE33eHtUiL2Ev_3UPkz3oQ3jUPqvei7XIHrBO_BMmUd85JzRyrC5OswcRlAOkvQ9nrMnsIhrG8FmbgQXoJ6_u5i8dVJHa-UwtvvU1vUo-QYCygh1HE8NfatF_bW2-XXrZOLvlEVuaIYph0vMt9gUb8mawSTbIInnSZlTYfwJr9CVc9qyzYhYfSdKjdJ1JkeFRW15XGP5ZXjNyQ',
      isv_customerIpAddress: '27.57.67.109',
      isv_maskedPan: '400000XXXXXX1091',
      isv_cardExpiryMonth: '01',
      isv_deviceDataCollectionUrl: 'https://centinelapistag.cardinalcommerce.com/V1/Cruise/Collect',
      isv_cardinalReferenceId: 'b0c79f37-281e-4f09-a7a1-8ed01a459f20',
      isv_requestJwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxNTJjOWM4Yi1mNzQ1LTRjMTMtYmM1Yi0xMzg4NjI2NzI1NDciLCJpYXQiOjE2NDg2NDI5NzYsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0ODY0NjU3NiwiT3JnVW5pdElkIjoiNWEzZDAxZmU2ZmUzZDExMjdjZGJjOTFlIiwiUmVmZXJlbmNlSWQiOiJiMGM3OWYzNy0yODFlLTRmMDktYTdhMS04ZWQwMWE0NTlmMjAifQ.ewcXvvaNDlHWMNIJc8zvSOxLwB200etnHgiVIJojLbI',
      isv_tokenCaptureContextSignature: 'eyJraWQiOiJ6dSIsImFsZyI6IlJTMjU2In0.eyJmbHgiOnsicGF0aCI6Ii9mbGV4L3YyL3Rva2VucyIsImRhdGEiOiJJVzh1U2NXT3dmbHZCS0s4aVRuRER4QUFFQS9rTVBkQStYd04yQmZBeEVLbHVtMXJiUEdUMkpNeFQvRk9lOC92V2VwNFlMYVJsUTFBUisrTVRlN0xPTU5kTmVVbUdDU0l6cFpPaTZ4UFdpb1dFdXhMaG9PWFgxWnVkVDhrMzNoK0RCL2oiLCJvcmlnaW4iOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbSIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6ImVuYyIsIm4iOiJrQWJ2M0ZNcFk5cHZxc1JZc1QyeU1PdkFoZUlkVi1VNm9WNDdqclJCRTd3dF93eGVJTzRqUzEyMUp2U0szMU5yeGVnWExTcWdFVUczSTFVUWRESGJONXlOYmJUMzluT2EzckxOT0g1di0yVEhpUGp3Y0RYX2ZBeW1CRG1QWnU2N0w1SDdCZXZYRXdnTk9tR1RXX3B6LUZKemRYVGh3MHV6QnZPRktNVXYtNXNoSm9nRjBrOEhMajdka1cyWG5nVUNJT1ZwNkJ1TDJmNW15bWhsUjhmSWF6Y3NIejlYLUVhRkVGUF9EWU9zVmFtNnRzc2s2TF8zdXpUOGNNckt1amRZVktnVWs0Ym5EdVBrQXFFSV81ay1IYnByQm43SUxJRGJ5MGJKa3E3NVY4Mm82TFhKVEc3cnpSQkhTVFU5T3haYmdaS0pZOWw4M1AyZjhKcERzNlJZNHciLCJraWQiOiIwODVJUUxGaENrVmFmcUxLa1RBNnBGMWdIZmNGZ1ROOCJ9fSwiY3R4IjpbeyJkYXRhIjp7InRhcmdldE9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sIm1mT3JpZ2luIjoiaHR0cHM6Ly90ZXN0ZmxleC5jeWJlcnNvdXJjZS5jb20ifSwidHlwZSI6Im1mLTAuMTEuMCJ9XSwiaXNzIjoiRmxleCBBUEkiLCJleHAiOjE2NDg2NDM4NjAsImlhdCI6MTY0ODY0Mjk2MCwianRpIjoiQmpvRDMwY2Y0WFBzV25rUSJ9.gqAJLWLjy44aZ1mADZPkArcfag870e0ELdC1cpybFsqHQx6RvPLEa506dg31cncqtPRL6wH4IIqTaPqWU7zpe-iNlSs7Ja3Fk3nl9quOjSysgK4xs3PD7ozlIhJ29-GmDhlamFbCRqhnjFa6wCbf3s7vy5gyckAXIWNyK3K1OZDgogkMHzpLorLYRQTVFdzImS6pjpVvjHn6B4pGuVVOgDgFCdlsKKs4uXAU8c8P_jWNWU37TxLPCpEoiqIkhaCG_Wz7gtplIcIifeU1OlLpprv_RPyu-g1qLzLLYQvF1eQFJ4vDBoWhNSCClXZXloGd1WRxAI0iq5MpI5wcuqnLdQ',
      isv_acceptHeader: '*/*',
      isv_cardType: '001',
      isv_userAgentHeader: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36',
      isv_tokenVerificationContext: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbHgiOnsicGF0aCI6Ii9mbGV4L3YyL3Rva2VucyIsImRhdGEiOiJJVzh1U2NXT3dmbHZCS0s4aVRuRER4QUFFQS9rTVBkQStYd04yQmZBeEVLbHVtMXJiUEdUMkpNeFQvRk9lOC92V2VwNFlMYVJsUTFBUisrTVRlN0xPTU5kTmVVbUdDU0l6cFpPaTZ4UFdpb1dFdXhMaG9PWFgxWnVkVDhrMzNoK0RCL2oiLCJvcmlnaW4iOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbSIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6ImVuYyIsIm4iOiJrQWJ2M0ZNcFk5cHZxc1JZc1QyeU1PdkFoZUlkVi1VNm9WNDdqclJCRTd3dF93eGVJTzRqUzEyMUp2U0szMU5yeGVnWExTcWdFVUczSTFVUWRESGJONXlOYmJUMzluT2EzckxOT0g1di0yVEhpUGp3Y0RYX2ZBeW1CRG1QWnU2N0w1SDdCZXZYRXdnTk9tR1RXX3B6LUZKemRYVGh3MHV6QnZPRktNVXYtNXNoSm9nRjBrOEhMajdka1cyWG5nVUNJT1ZwNkJ1TDJmNW15bWhsUjhmSWF6Y3NIejlYLUVhRkVGUF9EWU9zVmFtNnRzc2s2TF8zdXpUOGNNckt1amRZVktnVWs0Ym5EdVBrQXFFSV81ay1IYnByQm43SUxJRGJ5MGJKa3E3NVY4Mm82TFhKVEc3cnpSQkhTVFU5T3haYmdaS0pZOWw4M1AyZjhKcERzNlJZNHciLCJraWQiOiIwODVJUUxGaENrVmFmcUxLa1RBNnBGMWdIZmNGZ1ROOCJ9fSwiY3R4IjpbeyJkYXRhIjp7InRhcmdldE9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sIm1mT3JpZ2luIjoiaHR0cHM6Ly90ZXN0ZmxleC5jeWJlcnNvdXJjZS5jb20ifSwidHlwZSI6Im1mLTAuMTEuMCJ9XSwiaXNzIjoiRmxleCBBUEkiLCJleHAiOjE2NDg2NDM4NjAsImlhdCI6MTY0ODY0Mjk2MCwianRpIjoiQmpvRDMwY2Y0WFBzV25rUSJ9.0rwH22Eb51O6y8W2EzRHGkEtR7kAEG2HMPAbSh0kYdM'
    }
  },
  paymentStatus: {},
  transactions: [],
  interfaceInteractions: []
}

export const getUpdateTokenActionsActions =
[
  '{"alias":"4111card","value":"DB0B315B52BABC38E053AF598E0A8268","paymentToken":"DB0B3127886FBB46E053AF598E0AF2A5","instrumentIdentifier":"7010000000121591111","cardType":"001","cardName":"001","cardNumber":"411111XXXXXX1111","cardExpiryMonth":"01","cardExpiryYear":"2026","flag":"updated"}',
  '{"alias":"1091card","value":"DB0B315B52BABC38E053AF598E0A8268","paymentToken":"DB476FB611F49979E053AF598E0A0DE1","instrumentIdentifier":"7020000000005531091","cardType":"001","cardName":"001","cardNumber":"400000XXXXXX1091","cardExpiryMonth":"01","cardExpiryYear":"2026","flag":"updated"}'
]

export const failurePaymentResponse =
{
  "httpCode": 201,
  "transactionId": "6437973031316274803954",
  "status": "DECLINED",
  "data": {
    "id": "6437973031316274803954",
    "submitTimeUtc": "2022-02-02T10:21:43Z",
    "status": "DECLINED",
    "errorInformation": {
      "reason": "DECISION_PROFILE_REJECT",
      "message": "The order has been rejected by Decision Manager"
    },
    "clientReferenceInformation": {
      "code": "2d2f0cdb-e057-41f5-81f9-d98da238c3f2"
    },
    "processingInformation": {
      "paymentSolution": "012"
    },
    "paymentInformation": {
      "scheme": "VISA CREDIT",
      "bin": "411111",
      "accountType": "Visa Gold",
      "issuer": "RIVER VALLEY CREDIT UNION",
      "binCountry": "US"
    },
    "riskInformation": {
      "profile": {},
      "infoCodes": {
        "customerList": [
          "NEG-AFCB",
          "NEG-CC",
          "NEG-EM",
          "NEG-FCB"
        ],
        "deviceBehavior": [
          "KeyMouseDisabled"
        ],
        "suspicious": [
          "RISK-GEO"
        ],
        "globalVelocity": [
          "VELL-FP",
          "VELS-FP",
          "VELS-TIP",
          "VELV-EM"
        ]
      },
      "casePriority": 3,
      "localTime": "0:21:43",
      "score": {
        "factorCodes": [
          "F",
          "G",
          "V"
        ],
        "modelUsed": "default",
        "result": "42"
      },
      "providers": {}
    },
    "consumerAuthenticationInformation": {}
  }
}

export const failureResponseTransactionDetail =
{
  id: 'fa4185f4-3e11-49f8-bbbe-9982e1f7ab68',
  timestamp: '2022-01-17T07:13:19.814Z',
  type: 'Authorization',
  amount: {
    type: 'centPrecision',
    currencyCode: 'USD',
    centAmount: 5980,
    fractionDigits: 2
  },
  state: 'Initial'
}

export const deleteTokenResponse = {
  httpCode: 204,
  message: '',
  deletedToken: 'DC2417E36C42D8ADE053AF598E0A1705'
}

export const deleteTokenCustomerObj = 
{
  "id": "def6c669-eed5-4c57-ba2e-5fb04bfed1fa",
  "version": 6,
  "lastMessageSequenceNumber": 1,
  "createdAt": "2022-04-08T11:20:47.143Z",
  "lastModifiedAt": "2022-04-08T11:51:03.132Z",
  "lastModifiedBy": {
    "clientId": "IDntqVHAxvMRxkMJfC5wFN6x",
    "isPlatformClient": false
  },
  "createdBy": {
    "clientId": "0GrQ8c2D9t1iSjzJF8E3Ygu3",
    "isPlatformClient": false,
    "customer": {
      "typeId": "customer",
      "id": "b0c50186-fc83-4a97-9ea3-47bab58b3cc6"
    }
  },
  "email": "sp@gmail.com",
  "firstName": "Shakshi ",
  "lastName": "Poddar",
  "password": "****9nM=",
  "addresses": [],
  "shippingAddressIds": [],
  "billingAddressIds": [],
  "isEmailVerified": false,
  "custom": {
    "type": {
      "typeId": "type",
      "id": "03554714-1432-43ab-9f63-8c31dc396982"
    },
    "fields": {
      "isv_tokens": [
        "{\"alias\":\"1091 31card\",\"value\":\"DC23E657AA7749A4E053AF598E0AF2E6\",\"paymentToken\":\"DC23CAF2946BDDE9E053AF598E0A482D\",\"instrumentIdentifier\":\"7020000000005531091\",\"cardType\":\"001\",\"cardName\":\"001\",\"cardNumber\":\"400000XXXXXX1091\",\"cardExpiryMonth\":\"01\",\"cardExpiryYear\":\"2031\"}",
        "{\"alias\":\"1111 25card\",\"value\":\"DC23E657AA7749A4E053AF598E0AF2E6\",\"paymentToken\":\"DC2417E36C42D8ADE053AF598E0A1705\",\"instrumentIdentifier\":\"7010000000121591111\",\"cardType\":\"001\",\"cardName\":\"001\",\"cardNumber\":\"411111XXXXXX1111\",\"cardExpiryMonth\":\"01\",\"cardExpiryYear\":\"2025\"}"
      ]
    }
  },
  "stores": [],
  "authenticationMode": "Password"
}
